# eon-all.yaml

# 1) MySQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
...
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
...
---
# 2) Backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
...
---
apiVersion: v1
kind: Service
metadata:
  name: backend
...
---
# 3) Frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
...
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
...
